### ISSUE TITLE
Error when running docker-compose up

### ISSUE THREAD

**Issue by BillyTheCowBoy** [fcrepo-exts/fcrepo-docker#7]
Hi , i have encounter a problem when i run docker-compose up ,i am stuck at step 13/15
it seems like some of file is missing .

Step 13/15 : RUN cd /tmp        && curl -fSL https://github.com/fcrepo4/fcrepo4/releases/download/fcrepo-$FEDORA_TAG/fcrepo-webapp-$FEDORA_TAG.war -o fcrepo.war        && cp fcrepo.war /usr/local/tomcat/webapps/fcrepo.war
 ---> Running in ec07a8db8149
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
ERROR: Service 'fcrepo' failed to build: The command '/bin/sh -c cd /tmp        && curl -fSL https://github.com/fcrepo4/fcrepo4/releases/download/fcrepo-$FEDORA_TAG/fcrepo-webapp-$FEDORA_TAG.war -o fcrepo.war        && cp fcrepo.war /usr/local/tomcat/webapps/fcrepo.war' returned a non-zero code: 22

**Comment by awoods** [comment]
Hello @BillyTheCowBoy .

Are you on the `main` branch? Which instructions are are you using? The [README](https://github.com/fcrepo4-labs/fcrepo-docker/blob/main/README.md) suggests the following command:
```
docker run -p8080:8080 --name=fcrepo fcrepo/fcrepo
```

**Comment by billyhiuwali** [comment]
Thank you Awoods . my problem is fixed . 
it was because I forgot to select the proper Fedora version  **$FEDORA_TAG**
